name: 'Install Dependencies'
description: 'Install and cache Go modules'
runs:
  using: "composite"
  steps:
    - name: Get go mod cache path
      id: go-mod-cache-dir-path
      run: echo "::set-output name=dir::$(go env GOMODCACHE)"
      shell: bash

    - name: Cache go mod dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.go-mod-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-gomod-

    - name: Download dependencies
      run: go get -d -t ./...
      shell: bash
